// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Zkvu60tx5NiidRnXHtWzNutTHCOP7d8',
    appId: '1:614661538875:web:16bee478896c20fec8881e',
    messagingSenderId: '614661538875',
    projectId: 'finance-37241',
    authDomain: 'finance-37241.firebaseapp.com',
    storageBucket: 'finance-37241.firebasestorage.app',
    measurementId: 'G-MTWQLL8VZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrrGUVeGfBIpzSsMP_bi0OCwTy3KYC2mg',
    appId: '1:614661538875:android:478042717663c97dc8881e',
    messagingSenderId: '614661538875',
    projectId: 'finance-37241',
    storageBucket: 'finance-37241.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt9UubERiJTPhZ92qU1cz6l-ueJWv9PxA',
    appId: '1:614661538875:ios:b3cd17f769879427c8881e',
    messagingSenderId: '614661538875',
    projectId: 'finance-37241',
    storageBucket: 'finance-37241.firebasestorage.app',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt9UubERiJTPhZ92qU1cz6l-ueJWv9PxA',
    appId: '1:614661538875:ios:b3cd17f769879427c8881e',
    messagingSenderId: '614661538875',
    projectId: 'finance-37241',
    storageBucket: 'finance-37241.firebasestorage.app',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7Zkvu60tx5NiidRnXHtWzNutTHCOP7d8',
    appId: '1:614661538875:web:fdcbc30cf0ca56e3c8881e',
    messagingSenderId: '614661538875',
    projectId: 'finance-37241',
    authDomain: 'finance-37241.firebaseapp.com',
    storageBucket: 'finance-37241.firebasestorage.app',
    measurementId: 'G-BTN5F7JLKS',
  );
}
